apiVersion: v1
kind: Service
metadata:
  name: svc-web
  namespace: training
  labels:
    app.kubernetes.io/name: web-training
spec:
  selector:
    app.kubernetes.io/name: web-training
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
 