---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1
  namespace: training
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/vol1
    server: 192.168.56.11